/*
  # Seed products data

  1. Insert sample products data
    - Seeds, fertilizers, pesticides, and farm equipment
    - All data converted to match the database schema
    - Includes realistic Tanzanian agricultural products
*/

-- Insert products data
INSERT INTO products (
  name,
  category,
  category_id,
  price_amount,
  price_currency,
  weight,
  volume,
  length,
  capacity,
  sku,
  brand,
  img,
  key_features,
  description,
  usage_instructions,
  benefits,
  specifications,
  stock_status,
  quantity_in_stock,
  discount,
  availability,
  tags,
  rating,
  reviews_count,
  created_at,
  updated_at
) VALUES 
(
  'Dhahabu F1 Tomato Seeds',
  'Seed',
  'c1',
  380000,
  'TSh',
  '25g',
  NULL,
  NULL,
  NULL,
  'DHF1-TS-25G',
  'East-West Seed',
  'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['High-yield F1 hybrid (East-West Seed)', 'Strong plant vigour and uniform fruit set', 'Good disease resistance (locally tested in Mbeya)'],
  'Premium F1 hybrid tomato seeds offering high yields, strong growth, and resilience—ideal for smallholder and commercial production across Tanzania.',
  ARRAY['Sow in nursery 6–8 weeks before transplant', 'Transplant when 4–5 true leaves appear', 'Recommended seeding: 1 g yields ~1,000 seedlings', 'Plant spacing: 50 cm × 50 cm; water regularly'],
  ARRAY['Yields increase by 30–40% over open-pollinated types', 'Uniform fruiting and harvest', 'Tolerant to common local diseases', 'Proven in Mbeya farmer trials'],
  '{"type": "F1 Hybrid Seeds", "days_to_maturity": "70–75 days", "origin": "East-West Seed / AgricPays Tanzania"}',
  'In Stock',
  500,
  0,
  ARRAY['Tanzania'],
  ARRAY['seeds', 'tomato', 'hybrid', 'agriculture', 'high-yield'],
  4.5,
  120,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'SeedCo Maize Seed',
  'Seed',
  'c1',
  13000,
  'TSh',
  '2kg',
  NULL,
  NULL,
  NULL,
  'SC-MS-2KG',
  'SeedCo',
  'https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['High-yield hybrid variety suited for Tanzanian zones', 'Good early vigor and standability'],
  'Certified SeedCo hybrid maize seed, bred for adaptability across agro-ecological zones, ensuring reliable harvests and farmer returns.',
  ARRAY['Plant at 50 cm × 25 cm spacing (approx. 80,000 plants/ha)', 'Apply fertilizer at planting (e.g., 50 kg DAP + 50 kg CAN/ acre)', 'Provide supplemental irrigation or timely rainfall'],
  ARRAY['Reliable yield potential: 5–7 t/ha under good conditions', 'Balanced maturity for dual-season planting', 'Disease resilience supported by regional trials'],
  '{"type": "Hybrid maize seeds", "origin": "SeedCo Tanzania"}',
  'In Stock',
  1000,
  0,
  ARRAY['Tanzania'],
  ARRAY['seeds', 'maize', 'hybrid', 'agriculture', 'high-yield'],
  4.3,
  85,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'East–West Watermelon Seeds',
  'Seed',
  'c1',
  110000,
  'TSh',
  '50g',
  NULL,
  NULL,
  NULL,
  'EW-WMS-50G',
  'East-West Seed',
  'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['Premium F1 hybrid (East–West Seed)', 'High sugar content and uniform fruit shape', 'Strong disease and pest resistance'],
  'Top-tier hybrid watermelon seeds delivering sweet, attractive fruit ideal for local markets and export.',
  ARRAY['Seed: 3–4 cm deep in beds or mounds', 'Plant 2–3 seeds per hole, thin to 1 vigorous plant after emergence', 'Spacing: 1 m × 1 m', 'Irrigate regularly until fruit set, then reduce'],
  ARRAY['Up to 35% higher yield vs. local varieties', 'Uniform fruit quality commands premium prices', 'Good market appeal due to sweetness and size'],
  '{"type": "F1 Hybrid Seeds", "origin": "East–West Seed Tanzania"}',
  'In Stock',
  300,
  0,
  ARRAY['Tanzania'],
  ARRAY['seeds', 'watermelon', 'hybrid', 'agriculture', 'sweet'],
  4.7,
  95,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'YaraVita Crop Boost',
  'Fertilizer',
  'c2',
  120000,
  'TSh',
  NULL,
  '500ml',
  NULL,
  NULL,
  'YV-CB-500ML',
  'Yara',
  'https://images.pexels.com/photos/2423528/pexels-photo-2423528.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['Concentrated phosphate, magnesium, zinc foliar nutrient', 'Rapid absorption, ideal during flowering and stress periods'],
  'Yara''s foliar fertilizer helps unlock yield potential by addressing nutritional needs during critical growth phases.',
  ARRAY['Dilute 50 ml in 20 L water; spray during early flowering or stress', 'Use every 10–14 days or as agronomist recommends', 'Compatible with many crop protection products'],
  ARRAY['Enhances flowering and fruit set', 'Supports root strength and pest resistance', 'Maximizes nutrient use efficiency'],
  '{"type": "Foliar phosphate micronutrient mix", "pack_sizes": ["500ml", "1L", "5L"], "composition": "P₂O₅ 44%, K₂O 7.5%, MgO 4%, Zn 4.6%"}',
  'In Stock',
  200,
  0,
  ARRAY['Tanzania'],
  ARRAY['fertilizer', 'foliar', 'nutrient', 'agriculture', 'crop-boost'],
  4.4,
  60,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  '100 m Irrigation Hose',
  'Farm Equipment',
  'c5',
  320000,
  'TSh',
  NULL,
  NULL,
  '100m',
  NULL,
  'IH-PVC-100M',
  'Generic',
  'https://images.pexels.com/photos/4505165/pexels-photo-4505165.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['Durable PVC/PE construction', 'Smooth interior for efficient flow', 'UV-resistant and flexible for field use'],
  'A reliable 100 m irrigation hose suitable for gravity or pump-based watering systems in smallholder farms.',
  ARRAY['Lay hose along crop beds; connect to water source (tank/pump)', 'Use end-cap or dripper attachments as needed', 'Clean and store in shade after use'],
  ARRAY['Enables consistent irrigation delivery', 'Reduces labour and improves crop yields', 'Long service life with minimal maintenance'],
  '{"type": "Flat irrigation hose", "diameter": "2–3″ typical", "origin": "Local import (PVC/PE)"}',
  'In Stock',
  150,
  0,
  ARRAY['Tanzania'],
  ARRAY['irrigation', 'hose', 'farm-equipment', 'agriculture', 'durable'],
  4.2,
  45,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'Bravo 200 EC',
  'Pesticide',
  'c3',
  25000,
  'TSh',
  NULL,
  '100ml',
  NULL,
  NULL,
  'BRV-200EC-100ML',
  'Generic',
  'https://images.pexels.com/photos/7728030/pexels-photo-7728030.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['Broad-spectrum insecticide', 'Effective against sucking pests like aphids and whiteflies', 'Systemic action for long-lasting protection'],
  'Bravo 200 EC is a systemic insecticide containing Imidacloprid, designed to protect crops from sucking pests by interfering with their nervous systems.',
  ARRAY['Dilute 5–10 ml per 20 L of water', 'Spray evenly on affected crops in early morning or late afternoon', 'Repeat after 7–10 days if pest pressure continues'],
  ARRAY['Quick knockdown of pests', 'Long residual effect', 'Compatible with many fungicides and foliar feeds'],
  '{"type": "Systemic Insecticide", "active_ingredient": "Imidacloprid 200 g/L", "origin": "Imported"}',
  'In Stock',
  400,
  0,
  ARRAY['Tanzania'],
  ARRAY['pesticide', 'insecticide', 'imidacloprid', 'agriculture', 'pest-control'],
  4.6,
  70,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'Abamite',
  'Pesticide',
  'c3',
  35000,
  'TSh',
  NULL,
  '100ml',
  NULL,
  NULL,
  'ABM-100ML',
  'Generic',
  'https://images.pexels.com/photos/7728030/pexels-photo-7728030.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['Controls mites, leaf miners, and other insects', 'Derived from natural soil microorganisms', 'Translaminar activity ensures internal leaf protection'],
  'Abamite is a highly effective miticide and insecticide based on Abamectin. It disrupts the nervous system of pests, offering long-lasting control.',
  ARRAY['Use 5–8 ml per 20 L of water', 'Apply at the first sign of infestation', 'Use protective gear while spraying'],
  ARRAY['Highly effective on hard-to-control mites', 'Low toxicity to beneficial insects', 'Safe interval before harvest'],
  '{"type": "Insecticide/Miticide", "active_ingredient": "Abamectin 1.8% EC", "origin": "Tanzania"}',
  'In Stock',
  350,
  0,
  ARRAY['Tanzania'],
  ARRAY['pesticide', 'miticide', 'abamectin', 'agriculture', 'pest-control'],
  4.5,
  55,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'Manual Knapsack Sprayer',
  'Farm Equipment',
  'c6',
  65000,
  'TSh',
  NULL,
  NULL,
  NULL,
  '16L',
  'MKS-16L',
  'Generic',
  'https://images.pexels.com/photos/2933243/pexels-photo-2933243.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['16-litre tank capacity', 'Durable plastic construction', 'Adjustable nozzle and comfortable shoulder straps'],
  'Manual knapsack sprayer for efficient pesticide and foliar application. Suitable for small-scale farmers and gardens.',
  ARRAY['Fill with water and chemical solution (as per product instructions)', 'Pump handle to build pressure', 'Spray evenly across crop foliage'],
  ARRAY['Reduces chemical wastage', 'Simple and affordable', 'Effective for wide field coverage'],
  '{"type": "Manual Sprayer", "material": "Plastic with metal lance", "origin": "Local and imported brands"}',
  'In Stock',
  250,
  0,
  ARRAY['Tanzania'],
  ARRAY['sprayer', 'farm-equipment', 'agriculture', 'pesticide-application'],
  4.3,
  80,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'Certified Rice Seed',
  'Seed',
  'c1',
  3000,
  'TSh',
  '1kg',
  NULL,
  NULL,
  NULL,
  'CRS-TARI-1KG',
  'TARI',
  'https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['High yield certified seed from TARI', 'Good resistance to local pests and diseases', 'Matures in 100–120 days'],
  'Officially released and certified rice seed from TARI, suitable for major rice growing areas in Tanzania.',
  ARRAY['Use 25–30 kg seed per acre', 'Soak and pre-germinate before broadcasting', 'Apply fertilizer and manage weeds early'],
  ARRAY['Yield up to 4–6 t/ha under good management', 'Uniform grain size and cooking quality', 'Suitable for irrigation and rainfed systems'],
  '{"type": "Certified Rice Seed", "variety": "TARI Improved Local", "maturity": "100–120 days", "origin": "TARI Tanzania"}',
  'In Stock',
  2000,
  0,
  ARRAY['Tanzania'],
  ARRAY['seeds', 'rice', 'certified', 'agriculture', 'high-yield'],
  4.4,
  65,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'Black Gram Seed',
  'Seed',
  'c1',
  5500,
  'TSh',
  '1kg',
  NULL,
  NULL,
  NULL,
  'BGS-UAS-1KG',
  'UAS Dharwad',
  'https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['Short duration legume (60–70 days)', 'Good for intercropping and rotation', 'Nitrogen fixing to improve soil fertility'],
  'UAS Dharwad variety black gram is ideal for farmers looking for short-term legumes with soil enrichment and market value benefits.',
  ARRAY['Use 8–10 kg/acre', 'Broadcast or drill in rows 30 cm apart', 'Ensure early weeding and watering during flowering'],
  ARRAY['Matures in 2–2.5 months', 'Improves soil health', 'Good demand in local and regional markets'],
  '{"type": "Legume Seed", "variety": "UAS Dharwad", "maturity": "60–70 days", "origin": "Imported"}',
  'In Stock',
  1500,
  0,
  ARRAY['Tanzania'],
  ARRAY['seeds', 'legume', 'black-gram', 'agriculture', 'soil-health'],
  4.2,
  50,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
),
(
  'YaraMila NPK 15-15-15 Fertilizer',
  'Fertilizer',
  'c2',
  75000,
  'TSh',
  '50kg',
  NULL,
  NULL,
  NULL,
  'YM-NPK-50KG',
  'YaraMila',
  'https://images.pexels.com/photos/2423528/pexels-photo-2423528.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  ARRAY['Balanced NPK ratio (15:15:15)', 'Enhances fruiting and flowering', 'Boosts vegetative and root development', 'Quick release', 'Granular form'],
  'YaraMila NPK 15-15-15 is a compound fertilizer providing equal proportions of essential nutrients. Ideal for various crops, it supports healthy growth and high yields.',
  ARRAY['Apply during early planting or after germination', 'Dosage: 40–80 kg/acre depending on crop', 'Spread evenly near root zone and cover with soil', 'Water after application for quick absorption', 'Avoid direct contact with seeds during planting'],
  ARRAY['Increases crop yield by up to 30%', 'Enhances root strength and nutrient uptake', 'Boosts resistance to pests and diseases', 'Improves flowering and fruiting consistency', 'Suitable for all major agro-climatic zones in Tanzania'],
  '{"type": "Compound Fertilizer", "form": "Granular", "nutrient_content": "15% N, 15% P₂O₅, 15% K₂O", "packaging": "50kg bags", "application_rate": "40-80 kg per acre", "origin": "YaraMila Tanzania"}',
  'In Stock',
  100,
  0,
  ARRAY['Tanzania'],
  ARRAY['fertilizer', 'npk', 'granular', 'agriculture', 'high-yield'],
  4.5,
  40,
  '2025-06-23T15:10:00Z',
  '2025-06-23T15:10:00Z'
);